### ISSUE TITLE
Feature: user defined functions to let users dynamically generate content

### ISSUE THREAD

**Issue by vigith** [xaviershay/grange-server#6]
Lot of us who use range have instances running in Amazon AWS where the node list is not static due the auto-scaling property of AMZ. IMHO we can solve this in following ways
1. manually edit content in YAML to keep it in sync
2. generate the YAML file automatically though a separate system
3. give an option to udf to generate the content

(1) is not an option because it won't scale. Problem with (2) is, if we use version control to version the changes in YAML file, we might run into race conditions where the final YAML files cannot be merged. 

(3) seems to be better because users can write their on functions to generate content on fly without the need of editing YAML file. Down side for this is, a slow user defined function will make the end point drag. (udf could be a REST call to make interaction easy).

```yaml
key1:
  - udf(fn(someargs))
```
where `udf` is a keyword to let the system know we are looking for at an user defined function, `fn` could be the function name with `someargs` as the argument passed to the function (or `fn` could be a REST endpoint using `someargs` as its GET param)

I am willing to write a patch if you are interested. Please feel to close the issue if you think it is not in the scope :-)

**Comment by xaviershay** [comment]
We use option 2 and it works pretty nicely. Since you can specify multiple yaml paths, you can be clear that the dynamically generated YAML "wins" and avoid conflicts.

I'm open to UDFs, as long as we maintain the invariant that the entire state is held in memory and any operations against it are pure functions that can be cached. If it's a patch to this repo, that would work. If it's a path to grange itself you'll need to be more careful.

See also https://github.com/xaviershay/grange-server/pull/4 for another alternative.

**Comment by senthilvel** [comment]
Love the consul integration.

**Comment by vigith** [comment]
I don't think UDFs are the right way to solve this.
